### ISSUE TITLE
Continuous integration with bitbucket: Bad path to redis_exec is given: /usr/local/bin/redis-server not exists or wrong program

### ISSUE THREAD

**Issue by benjaminweb** [ClearcodeHQ/pytest-redis#108]
### What action do you want to perform

* CI with bitbucket pipelines, using redis image as service, listening on localhost 6379

### What are the results

`E           pytest_redis.executor.RedisMisconfigured: Bad path to redis_exec is given: /usr/local/bin/redis-server not exists or wrong program`

### What are the expected results

Tests requiring `redisdb` fixture run fine.

---

Cross-posting https://community.atlassian.com/t5/Bitbucket-questions/How-do-I-use-Redis-in-Bitbucket-Pipelines/qaq-p/461915

**Comment by fizyk** [comment]
Are you able to provide/use single docker image with both python and redis?
pytest-redis does expect redis to be on the same machine, as it tries to start and configure redis by itself.

**Comment by benjaminweb** [comment]
Thanks for pointing me to the heart of my requirement: redis and python need to be on the same machine ;).
I wonder that a rough search did not yield any existing public docker image with redis and python.
It seems to me that it pytest-redis and bitbucket pipelines (images overlayed with services) are  incompatible in their default configuration.

**=> Do you know a docker image providing python and redis?**

**Comment by cans** [comment]
May I ask a silly question ? Why do you need `pytest-redis` for, if you use a side-car redis container alongside your python container ? (never used bitbucket CI but I guess that is what is going on) All you need is a fixture that gives you the network address of the side-car container (can probably get that from an environment variable or simply the hostname of the container is just `redis`) ... and have your tests talk to that redis. `pytest-redis` is for starting a redis-server at the moment you need it while you are running your tests, something the service container does too, but in a different way.

Pytest-redis:

      +------------------------------------------------------+
      |  Machine                                             | 
      |  +---------+                            +---------+  |
      |  | PyTest  |                            | Redis   |  |
      |  | process |  <-- loopback address -->  | process |  |
      |  +---------+                            +---------+  |
      +------------------------------------------------------+

Docker (on bitbucket or elsewere):

      +--------------------+                    +------------------+
      |  Python Container  |                    |  Redis Container |  
      |  +---------+       |                    |    +---------+   |
      |  | PyTest  |       |                    |    | Redis   |   |
      |  | process | <-----+-- docker network --+--> | process |   |
      |  +---------+       |                    |    +---------+   |
      +--------------------+                    +------------------+

**Comment by benjaminweb** [comment]
Thanks for your elaboration, @cans.
Your question is to the point: I *think* I need `pytest-redis` to run my tests via `tox` locally.
I try to build my bitbucket CI environment from my local environment. Clash. Since redis is not present.
Yup, substituting pytest-redis in favour of the address of redis, I feel I get that working.

=> But, how would I want to go for my local tox testing *without* a docker container running redis?

**Comment by fizyk** [comment]
To be able to test in both cases, I'd use separate fixture to provide either client, or docker address to the rest of the tests/fixtures. This fixture would have to detect whether tests are being run through tox locally or on a docker (env var?) and either return docker redis address or request local redis start using `request.getfixturevalue`

In one of our private projects we went actually the other way and installed redis on the docker with python:

```
FROM python:2.7-alpine as tester
RUN apk add --update redis
```

**Comment by benjaminweb** [comment]
https://confluence.atlassian.com/bitbucket/use-services-and-databases-in-bitbucket-pipelines-874786688.html reads

> No port mapping or hostnames are required. For example, if you were using Postgres, your tests just connect to port 5432 on localhost.

Just for clarification:

With this pytest.ini:
```
[pytest]
addopts = -vv
redis_host = 127.0.0.1
redis_port = 6379
```

I get a
```
E     pytest_redis.executor.RedisMisconfigured: Bad path to redis_exec is given: /usr/bin/redis-server not exists or wrong program
```

=> Is this expected behaviour?

=> @fizyk Can I get pytest-redis with command line switch `--redis-host=127.0.0.1` working _when_  redis service is provided by docker accessible on same host as described by bitbucket pipelines docs (see above)?

**Comment by fizyk** [comment]
@benjaminweb the problem here is, that currently, pytest-redis only connects to the one server it starts itself, and for that it needs path for the redis_exec, or redis installed on the same machine/image you run tests with pytest-redis.
That's why it works in your tox tests, where you have everything on he same machine, and doesn't on pipelines, where redis is separate docker container.

I don't mind having a separate fixture just for client to connect to any arbitrary redis server there is.
But on the other hand, if pytest-redis starts it's own redis isntance, then we're sure that the database is clean during every test.

**Comment by fizyk** [comment]
#196

**Comment by fizyk** [comment]
new version should cover this case
