### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by tony** [ClearcodeHQ/pytest-redis#136]
Hi, thank you for the project!

There are some situations where I can't use LGPL on some of my python projects. The reason why is the license isn't framed in the sense of a scripting language and it's quite a big list of terms compared to the alternatives. Is there any more information on using LGPL over the license pytest itself uses?

I can provide more details / specific cases if it's helpful. The reason why is when I brought LGPL to a lawyer (in USA) there were concerns with side effects that could happen down the road due to its language around derivatives. 

Are you open to using a license the same as pytest itself? If it were only for the sake of congruence with pytest and other pytest plugins?

**Comment by fizyk** [comment]
Hey @tony 
details use cases would definitely be helpful. We're specifically using an LGPL as it's pretty permissive, almost as permissive as MIT.

**Comment by tony** [comment]
@fizyk Thanks for addressing this issue!

LGPL is more permissive than GPL, and definitely more than AGPL.

However, since it's a software license, (I think?) being terse as necessary is a good rule to follow? Is there any particular reason / goal why LGPL is picked over MIT/BSD/ISC/etc?

(My assumption is when I see a license, the intention is to enforce it fully, I think it's fair to assume since written there and what is enforceable to the user?)

The specific reason I ask is I prefer to avoid incorporating licenses with anything wording that sounds like it could cause a derivative if used some way in the future. 

The other reason is this being a python package. For example, if a fellow programmer were to (years from now) decide to copy or vendorize the fixture from pytest-redis, they would be leaving themselves open to the project being a derivative.

My situation is I could use pytest-redis on a project, but if I could avoid the risk of pulling a package with a license that could cause complication down the line. (I do prefer pulling in plugins - part of the reason is I feel a lot safer with BSD/MIT/ISC for python packages).

**Comment by tony** [comment]
> (I do prefer pulling in pytest plugins instead of my own fixtures since they tend to be higher quality and get updates - part of the reason is I feel a lot safer with BSD/MIT/ISC for python packages).

Quoting myself. I forgot, I did ask request this with another pytest package a few years ago: https://github.com/pytest-dev/pytest-mock/issues/45

**Comment by fizyk** [comment]
@tony licenses are a bit hard to me, and each time I was discussing it with few people in my company and in the next few hours I forgot why exactly it's not a problem:

https://fosswire.com/post/2007/04/the-differences-between-the-gpl-lgpl-and-the-bsd/
https://github.com/kennethreitz/requests/issues/3389

If you do not modify the plugin's codebase and distribute it in a manner that it is distinct from your codebase (ie: and vendoring without modification is such), you are linking the code and not make a derivative work of it.

Although I agree having simpler, more permissive licenses would in best case save us from frying our brains trying to apprehend them, LGPL in this case doesn't impose any issue.

**Comment by felixriese** [comment]
I just found this project (really cool, thanks!) - and realized that for my use cases, only permissive licenses such as BSD/MIT/ISC work well.

If/when the contributors around @fizyk change the license, let me know.

**Comment by tony** [comment]
@fizyk I forgot about this since and moved on, but an interesting update:

> @tony licenses are a bit hard to me, and each time I was discussing it with few people in my company and in the next few hours I forgot why exactly it's not a problem:
> 
> https://fosswire.com/post/2007/04/the-differences-between-the-gpl-lgpl-and-the-bsd/ https://github.com/kennethreitz/requests/issues/3389

7 months ago (July 6th, 2021), they switched [`chardet`](https://pypi.org/project/chardet/) (LGPL) to an MIT licensed one, [`charset_normalizer`](https://pypi.org/project/charset-normalizer/):
- https://github.com/psf/requests/pull/5797
- https://github.com/psf/requests/commit/2ed84f55b22f19a1e1e8eea2e50963dce62052d3
  ```
  Although using the (non-vendored) chardet library is fine for requests
  itself, but using a LGPL dependency the story is a lot less clear
  for downstream projects, particularly ones that might like to bundle
  requests (and thus chardet) in to a single binary -- think something
  similar to what docker-compose is doing. By including an LGPL'd module
  it is no longer clear if the resulting artefact must also be LGPL'd.
  
  By changing out this dependency for one under MIT we remove all
  license ambiguity.
  
  As an "escape hatch" I have made the code so that it will use chardet
  first if it is installed, but we no longer depend upon it directly,
  although there is a new extra added, `requests[lgpl]`. This should
  minimize the impact to users, and give them an escape hatch if
  charset_normalizer turns out to be not as good. (In my non-exhaustive
  tests it detects the same encoding as chartdet in every case I threw at
  it)
  ```
