### ISSUE TITLE
setting --redis-exec through pytest args, changes rootdir of pytest

### ISSUE THREAD

**Issue by Sult** [ClearcodeHQ/pytest-redis#273]
### What action do you want to perform
I found weird behaviour that changes the early_config.rootdir of pytest, when you add the --redis-exec parameter as shell args instead of setup.cfg

On MacOS the exec path of redis is /usr/local/bin/redis-server, and because of System Integrity Protection
But because CI and servers run with ubuntu, I dont want to overwrite the setup.cfg.

### What are the results
When i use `pytest --redis-exec /usr/local/bin/redis-server` the rootdir of pytest jumps to 

```
MacBook-Pro:~/source/datau/dashboardu/python(node-walker)$ pytest --redis-exec /usr/local/bin/redis-server -s
> /Users/hansdejong/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pytest_env/plugin.py(26)pytest_load_initial_conftests()
-> for e in early_config.getini("env"):
(Pdb) early_config.rootdir
local('/usr/local/bin')

```

This results in the fact that pytest doesnt find any setup.cfg file anymore and your settings wont be picked up

When you put this setting inside the setup.cfg this doesnt happen.

### What are the expected results
using the setup.cfg setting or the shell args shouldnt change the behaviour of pytest rootdir

**Comment by fizyk** [comment]
@Sult I actually encountered this problem while working on pytest-elasticsearch. Solution was to write the command as `pytest --redis-exec=/usr/local/bin/redis-server`
