### ISSUE TITLE
[question] session scope fixture

### ISSUE THREAD

**Issue by woutdenolf** [ClearcodeHQ/pytest-redis#382]
Does `pytest-redis` have session scope fixtures? I want to to this by `redisdb` has the wrong scope:
```python
@pytest.fixture(scope="session")
def myfixture(redisdb):
    ...
```

**Comment by fizyk** [comment]
No, it does not. 
The redisdb goal, apart from providing a redis client for your test code, is to clean the database after each test, so you won't have leaked state between tests.

**Comment by woutdenolf** [comment]
Ok I understand. I'm using `pytest-redis` to instantiate a redis database as backend for [celery](https://github.com/celery/celery). In that case you don't need a clean database per test.

I did find a solution with `redis_proc`

```python
@pytest.fixture(scope="session")
def celery_config(redis_proc):
    url = f"redis://{redis_proc.host}:{redis_proc.port}"
    # celery -A ewoksjob.apps.ewoks --broker={url}/0 --result-backend={url}/1 inspect stats -t 5
    return {
        "broker_url": f"{url}/0",
        "result_backend": f"{url}/1",
        "result_serializer": "pickle",
        "accept_content": ["application/json", "application/x-python-serialize"],
    }
```

**Comment by fizyk** [comment]
If you don't have a need for a separate Redis client to actually look up in tests into the Redis to assert certain things, then that'd be the best solution I think.

**Comment by woutdenolf** [comment]
Indeed I don't need a direct Redis client in my tests.

I guess for other use cases which do need a direct Redis client, you could add fixture arguments to `factories.redisdb`:

```python
def redisdb(process_fixture_name, dbnum=0, strict=True, decode=None, **fixture_kwargs):

    @pytest.fixture(**fixture_kwargs)
    def redisdb_factory(request):
```

which can be used like this

```python
from pytest_redis import factories

redis_my_proc = factories.redis_proc(port=None)
redis_my = factories.redisdb('redis_my_proc', scope='session')
```
