### ISSUE TITLE
Is redis server being configured to not support pub/sub?

### ISSUE THREAD

**Issue by katetsu** [ClearcodeHQ/pytest-redis#384]
### What action do you want to perform
i have a client that publishes data to a redis end point. the client works with the redis-server running but i am getting an error if its run with pytest-redis.

### What are the results
`Failed to publish data with error: An error was signalled by the server: wrong number of arguments for 'publish' command`

### What are the expected results
no errors should come up.

**Comment by mguijarr** [comment]
I make extensive use of PUB/SUB , it works perfectly - I am not even sure if redis can be configured to not suppor pub/sub. I vote for closing this issue
