### ISSUE TITLE
Retry Support

### ISSUE THREAD

**Issue by romanofski** [ClearcodeHQ/pytest-redis#388]
### What action do you want to perform
We are running into occasional test failures, because of a race condition between test execution and the redis server accepting connections. When using the `redisdb` fixture, there seems to be no `Retry` policy setup, because by default the `Connection` class uses `NoBackoff`.

### What are the results
Test fixture waits until the server is ready before continuing.

I'd be happy to contribute this. 

Ideally if we could provide the `redis.retry.Retry` and `redis.backoff` module contents and accept an additional parameter from the caller to configure retries, it would probably be the least of effort?

**Comment by romanofski** [comment]
@fizyk Existing running redis server.

**Comment by romanofski** [comment]
> Okay the way I see it the Noop executor should rather check for the availability of the existing running server, and preferably employ same setting as regular RedisExecutor:
> 
> https://github.com/ClearcodeHQ/pytest-redis/blob/9f9cd4091cac69486ef8f81cef81c990301ea74c/src/pytest_redis/factories.py#L129

Currently the `NoopRedis` is just a named tuple. Would it be acceptable to turn that into a class, accept an additional `timeout` argument defaulting to 60 (like the `RedisExecutor`). Then it seems overwriting the `start` method would be where we could call the `self.wait_for` with a private method creating the socket connection and back off.

I haven't written any code, does that sound reasonable?

**Comment by fizyk** [comment]
Yes, it does :)
