### ISSUE TITLE
Add type annotations and py.typed

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-redis#422]
### What action do you want to perform

I want to use mypy in a package using pytest-redis for its tests.

### What are the results

```
error: Skipping analyzing "pytest_redis": module is installed, but missing library stubs or py.typed marker  [import]
```

### What are the expected results

Mypy successfully imports it and infers types for fixtures defined via pytest-redis factories.

**Comment by fizyk** [comment]
#428
