### ISSUE TITLE
Can't set up server with password

### ISSUE THREAD

**Issue by Anthchirp** [ClearcodeHQ/pytest-redis#441]
### What action do you want to perform

I want to use a redis server with a defined password.
So I add
```
redis_password = secret
```
to my `pytest.ini`

### What are the results

`ERROR: Unknown config option: redis_password`

### What are the expected results

This feature was introduced in #404 in August 2022, so it should just work.
However, I am using the most recent release on pypi (2.4.0), and that is from February 2022.

Could a new release be published?

**Comment by fizyk** [comment]
@Anthchirp had to perform some project maintenance first. Check 3.0.0 (is getting released at the moment - https://github.com/ClearcodeHQ/pytest-redis/blob/v3.0.0/CHANGES.rst)

**Comment by Anthchirp** [comment]
Hah. Excellent

Thank you!
