### ISSUE TITLE
py.typed not included in PyPI distribution

### ISSUE THREAD

**Issue by MaxwellPayne** [ClearcodeHQ/pytest-redis#470]
### What action do you want to perform

I'm attempting to import submodules of `pytest_redis` within my project, using version 3.0.1. Something like:
```python
import pytest_redis.executor
import pytest_redis.factories
```

### What are the results

When I run a `mypy` check on this file, I get the following errors:
```
tests/conftest.py:15: error: Skipping analyzing "pytest_redis.executor": module is installed, but missing library stubs or py.typed marker  [import]
    import pytest_redis.executor
    ^
tests/conftest.py:15: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
tests/conftest.py:15: error: Skipping analyzing "pytest_redis": module is installed, but missing library stubs or py.typed marker  [import]
    import pytest_redis.executor
    ^
tests/conftest.py:16: error: Skipping analyzing "pytest_redis.factories": module is installed, but missing library stubs or py.typed marker  [import]
    import pytest_redis.factories
```

### What are the expected results

This seemed strange to me, since I noticed that this project has a [py.typed](https://github.com/ClearcodeHQ/pytest-redis/blob/b3508f9d13a562aa6355ca6b0cb3a8bb18817a05/pytest_redis/py.typed) file which _should_ inform Mypy that this repo has type annotations in place. But when I looked in my local `site-packages/pytest_redis` directory, I see the following:
```
-rw-r--r--  1 max  staff   861 Apr 18 23:46 __init__.py
drwxr-xr-x  7 max  staff   224 Apr 19 01:08 __pycache__
-rw-r--r--  1 max  staff  1527 Apr 18 23:46 config.py
-rw-r--r--  1 max  staff   343 Apr 18 23:46 exception.py
drwxr-xr-x  6 max  staff   192 Apr 18 23:49 executor
drwxr-xr-x  7 max  staff   224 Apr 18 23:49 factories
-rw-r--r--  1 max  staff  5021 Apr 18 23:46 plugin.py
```
The lack of a local `py.typed` file misleads Mypy into believing that this package does not have type annotations, which is why it gives me those errors. When I manually touch a file with that name, Mypy then passes without error.

**Comment by fizyk** [comment]
@MaxwellPayne are you aware of any validation I could employ to check whether the py.typed is the package or not? Just In case I break something in the future again...

**Comment by fizyk** [comment]
Anyway, try 3.0.2

**Comment by MaxwellPayne** [comment]
@fizyk Thanks for the quick turnaround! I updated my package version to the new one from PyPI, and I see the expected `py.typed` file now. 

> are you aware of any validation I could employ to check whether the py.typed is the package or not? Just In case I break something in the future again...

I suppose you could write some sort of CI validation script that executes a build, tar-extracts the `dist/` artifact, then searches the resulting directory for `py.typed` and fails if not found. There might be a simpler way, however I'm pretty unfamiliar with the build process that uses `MANIFEST.in` so I can't speak to the most elegant solution.
