### ISSUE TITLE
bug introduced by commit c4276791713e47a76433122ddf7fdedb2a5a3d44 (pytest <=7.4.4)

### ISSUE THREAD

**Issue by mguijarr** [ClearcodeHQ/pytest-redis#677]
I am really sorry to say, a subtle bug has been introduced by this commit, and I didn't see it while doing the review 😫 

At the moment, `modules` is always `['']` which prevents Redis to start...
I wonder how it could pass all tests ?

In anyways, the fix is super easy, in file `pytest_redis/config.py` instead of:

```
if (modules := get_conf_option("modules")) is not None:
                                             ^^^^^^^^^^
        modules = modules.split(",")
else:
        modules = []
```

The config key is empty string so it is enough to make the test as: `if (modules := get_conf_option("modules")):`

Again, I apologize for not having seen it before.

**Comment by mguijarr** [comment]
The fix that works for me is #678

**Comment by mguijarr** [comment]
Hmm... My bad 🤔 In fact there seem to be no problem 😅 Sorry... Something remains in my code that is passing modules or something like this !

**Comment by fizyk** [comment]
Could be an empty call to modules @mguijarr

**Comment by mguijarr** [comment]
I identified the problem: the code in commit c4276791713e47a76433122ddf7fdedb2a5a3d44 does not work with pytest < 8.2

**Comment by mguijarr** [comment]
So, to keep compatibility with pytest <8 , I would recommend applying the proposed MR, if you want
